include make/config.mk
include make/target.mk
include make/paths.mk
include make/shared.mk
include make/flags.mk
include make/sources-app.mk
include make/sources-tools.mk
include make/sources-tests.mk
include make/objects.mk
include make/rules-build.mk
include make/rules-tools.mk
include make/rules-test.mk
include make/rules-memory-check.mk
include make/rules-ops.mk
include make/package-macos.mk
include make/release.mk
include make/phony.mk

-include $(DEPS)
