#ifndef MAPFORGE_MAP_TILE_LAYERS_H
#define MAPFORGE_MAP_TILE_LAYERS_H

typedef enum TileLayerKind {
    TILE_LAYER_ROAD_ARTERY = 0,
    TILE_LAYER_ROAD_LOCAL = 1,
    TILE_LAYER_CONTOUR = 2,
    TILE_LAYER_POLY_WATER = 3,
    TILE_LAYER_POLY_PARK = 4,
    TILE_LAYER_POLY_LANDUSE = 5,
    TILE_LAYER_POLY_BUILDING = 6,
    TILE_LAYER_COUNT = 7
} TileLayerKind;

#endif
