OBJS := $(patsubst src/%.c,$(APP_OBJ_DIR)/%.o,$(SRCS))
DEPS := $(OBJS:.o=.d)
DEPS += $(KIT_RENDER_EXTERNAL_TEXT_OBJ:.o=.d)
DEPS += $(KIT_RENDER_OBJ:.o=.d)
DEPS += $(KIT_RENDER_BACKEND_NULL_OBJ:.o=.d)
DEPS += $(KIT_RENDER_BACKEND_VK_OBJ:.o=.d)
DEPS += $(KIT_WORKSPACE_AUTHORING_OBJ:.o=.d)
DEPS += $(KIT_WORKSPACE_AUTHORING_UI_OVERLAY_OBJ:.o=.d)
DEPS += $(KIT_WORKSPACE_AUTHORING_UI_FONT_THEME_OBJ:.o=.d)
DEPS += $(VK_RENDERER_OBJS:.o=.d)
LINK_OBJS := $(OBJS)
CORE_SHARED_LIBS := $(CORE_TRACE_LIB) $(CORE_PACK_LIB) $(CORE_KERNEL_LIB) $(CORE_WAKE_LIB) $(CORE_WORKERS_LIB) $(CORE_JOBS_LIB) $(CORE_SCHED_LIB) $(CORE_QUEUE_LIB) $(CORE_TIME_LIB) $(CORE_HEADLESS_JOB_LIB) $(CORE_THEME_LIB) $(CORE_FONT_LIB) $(CORE_PANE_LIB) $(CORE_VIEWPORT2D_LIB) $(KIT_RUNTIME_DIAG_LIB) $(CORE_SPACE_LIB) $(CORE_IO_LIB) $(CORE_DATA_LIB) $(CORE_BASE_LIB)
LINK_OBJS += $(KIT_RENDER_EXTERNAL_TEXT_OBJ)
LINK_OBJS += $(KIT_RENDER_OBJ)
LINK_OBJS += $(KIT_RENDER_BACKEND_NULL_OBJ)
LINK_OBJS += $(KIT_RENDER_BACKEND_VK_OBJ)
LINK_OBJS += $(KIT_WORKSPACE_AUTHORING_OBJ)
LINK_OBJS += $(KIT_WORKSPACE_AUTHORING_UI_OVERLAY_OBJ)
LINK_OBJS += $(KIT_WORKSPACE_AUTHORING_UI_FONT_THEME_OBJ)
LINK_OBJS += $(CORE_SHARED_LIBS)
TARGET := $(APP_BIN)

ifeq ($(VK_APP_ENABLED),1)
APP_CFLAGS += -I$(VK_RENDERER_INCLUDE) -DMAPFORGE_HAVE_VK=1 -DVK_RENDERER_SHADER_ROOT=\"$(VK_RENDERER_RESOLVED_DIR)\"
HOST_CFLAGS += -I$(VK_RENDERER_INCLUDE) -DMAPFORGE_HAVE_VK=1 -DVK_RENDERER_SHADER_ROOT=\"$(VK_RENDERER_RESOLVED_DIR)\"
LINK_OBJS += $(VK_RENDERER_OBJS)
LDLIBS += $(VULKAN_LIBS) -framework Metal -framework QuartzCore -framework Cocoa -framework IOKit -framework CoreVideo
endif
