APP_CC := $(if $(filter fisics,$(BUILD_TOOLCHAIN)),$(FISICS_CC),$(HOST_CC))
APP_COMPILER_DEP := $(if $(filter fisics,$(BUILD_TOOLCHAIN)),$(FISICS_CC),)
BUILD_ROOT := build
TARGET_BUILD_ROOT := $(BUILD_ROOT)/targets/$(TARGET_TRIPLE)
HOST_BUILD_ROOT := $(TARGET_BUILD_ROOT)/host
APP_TOOLCHAIN_ROOT := $(TARGET_BUILD_ROOT)/toolchains/$(BUILD_TOOLCHAIN)
APP_OBJ_DIR := $(APP_TOOLCHAIN_ROOT)/obj
APP_BIN_DIR := $(APP_TOOLCHAIN_ROOT)/bin
APP_BIN := $(APP_BIN_DIR)/mapforge
APP_COMPILER_STAMP := $(APP_TOOLCHAIN_ROOT)/.compiler_stamp
PACKAGE_BIN := $(TARGET_BUILD_ROOT)/toolchains/$(PACKAGE_TOOLCHAIN)/bin/mapforge
TEST_APP_BIN := $(TARGET_BUILD_ROOT)/toolchains/$(TEST_TOOLCHAIN)/bin/mapforge
SHARED_BUILD_DIR := $(TARGET_BUILD_ROOT)/shared
TOOL_BIN_DIR := $(TARGET_BUILD_ROOT)/tools
TEST_BIN_DIR := $(TARGET_BUILD_ROOT)/tests

DIST_DIR := $(TARGET_BUILD_ROOT)/dist
PACKAGE_APP_NAME := Carta.app
PACKAGE_APP_DIR := $(DIST_DIR)/$(PACKAGE_APP_NAME)
PACKAGE_CONTENTS_DIR := $(PACKAGE_APP_DIR)/Contents
PACKAGE_MACOS_DIR := $(PACKAGE_CONTENTS_DIR)/MacOS
PACKAGE_HELPERS_DIR := $(PACKAGE_CONTENTS_DIR)/Helpers
PACKAGE_RESOURCES_DIR := $(PACKAGE_CONTENTS_DIR)/Resources
PACKAGE_FRAMEWORKS_DIR := $(PACKAGE_CONTENTS_DIR)/Frameworks
PACKAGE_TOOLS_DIR := $(PACKAGE_HELPERS_DIR)
PACKAGE_INFO_PLIST_SRC := tools/packaging/macos/Info.plist
PACKAGE_LAUNCHER_SCRIPT_SRC := tools/packaging/macos/mapforge-launcher
PACKAGE_LAUNCHER_NATIVE_SRC := tools/packaging/macos/mapforge-launcher.c
PACKAGE_LAUNCHER_SCRIPT_PATH := $(PACKAGE_RESOURCES_DIR)/mapforge-launcher.sh
PACKAGE_DYLIB_BUNDLER := tools/packaging/macos/bundle-dylibs.sh
PACKAGE_APP_ICON_NAME := AppIcon
PACKAGE_APP_ICON_FILE := $(PACKAGE_APP_ICON_NAME).icns
PACKAGE_LOCAL_ICON_DIR := tools/packaging/macos/local_app_icon
PACKAGE_APP_ICON_SRC ?= $(PACKAGE_LOCAL_ICON_DIR)/$(PACKAGE_APP_ICON_FILE)
PACKAGE_APP_ICONSET_SRC ?= $(PACKAGE_LOCAL_ICON_DIR)/$(PACKAGE_APP_ICON_NAME).iconset
PACKAGE_BUNDLED_ICON_PATH := $(PACKAGE_RESOURCES_DIR)/$(PACKAGE_APP_ICON_FILE)
DESKTOP_APP_DIR ?= $(HOME)/Desktop/$(PACKAGE_APP_NAME)
PACKAGE_ADHOC_SIGN_IDENTITY ?= -
PACKAGED_HELPER_TOOL_NAMES := mapforge_region mapforge_region_validate mapforge_graph
PACKAGED_HELPER_TOOLS := $(foreach tool,$(PACKAGED_HELPER_TOOL_NAMES),$(PACKAGE_TOOLS_DIR)/$(tool))

# RL0 release contract (pilot lock).
RELEASE_VERSION_FILE ?= VERSION
RELEASE_VERSION ?= $(strip $(shell cat "$(RELEASE_VERSION_FILE)" 2>/dev/null))
ifeq ($(RELEASE_VERSION),)
RELEASE_VERSION := 0.1.0
endif
RELEASE_CHANNEL ?= stable
RELEASE_PRODUCT_NAME := Carta
RELEASE_PROGRAM_KEY := map_forge
RELEASE_BUNDLE_ID := com.cosm.carta
RELEASE_ARTIFACT_BASENAME := $(RELEASE_PRODUCT_NAME)-$(RELEASE_VERSION)-$(RELEASE_PLATFORM)-$(RELEASE_ARCH)-$(RELEASE_CHANNEL)
# May be supplied by the Production Registry as a job-scoped relative root.
# Keep the ordinary developer default for manual local releases.
RELEASE_ROOT ?= build/release
RELEASE_DIR := $(RELEASE_ROOT)
RELEASE_APP_ZIP := $(RELEASE_DIR)/$(RELEASE_ARTIFACT_BASENAME).zip
RELEASE_APP_ZIP_SHA256 := $(RELEASE_APP_ZIP).sha256
RELEASE_MANIFEST := $(RELEASE_DIR)/$(RELEASE_ARTIFACT_BASENAME).manifest.txt
RELEASE_CODESIGN_IDENTITY ?= $(if $(strip $(APPLE_SIGN_IDENTITY)),$(APPLE_SIGN_IDENTITY),$(PACKAGE_ADHOC_SIGN_IDENTITY))
# Export/signing contract variables are intentionally unset by default.
APPLE_SIGN_IDENTITY ?=
APPLE_NOTARY_PROFILE ?=
APPLE_TEAM_ID ?=
STAPLE_MAX_ATTEMPTS ?= 6
STAPLE_RETRY_DELAY_SEC ?= 15
