SHARED_ROOT ?= third_party/codework_shared
SHARED_WORKSPACE_DIR ?= ../shared
CORE_SPACE_DIR := $(SHARED_ROOT)/core/core_space
CORE_BASE_DIR := $(SHARED_ROOT)/core/core_base
CORE_IO_DIR := $(SHARED_ROOT)/core/core_io
CORE_DATA_DIR := $(SHARED_ROOT)/core/core_data
CORE_PACK_DIR := $(SHARED_ROOT)/core/core_pack
CORE_TIME_DIR := $(SHARED_ROOT)/core/core_time
CORE_QUEUE_DIR := $(SHARED_ROOT)/core/core_queue
CORE_SCHED_DIR := $(SHARED_ROOT)/core/core_sched
CORE_JOBS_DIR := $(SHARED_ROOT)/core/core_jobs
CORE_WORKERS_DIR := $(SHARED_ROOT)/core/core_workers
CORE_WAKE_DIR := $(SHARED_ROOT)/core/core_wake
CORE_KERNEL_DIR := $(SHARED_ROOT)/core/core_kernel
CORE_TRACE_DIR := $(SHARED_ROOT)/core/core_trace
CORE_HEADLESS_JOB_DIR := $(SHARED_ROOT)/core/core_headless_job
CORE_THEME_DIR := $(SHARED_ROOT)/core/core_theme
CORE_FONT_DIR := $(SHARED_ROOT)/core/core_font
CORE_PANE_DIR := $(SHARED_ROOT)/core/core_pane
CORE_VIEWPORT2D_DIR := $(SHARED_ROOT)/core/core_viewport2d
KIT_RUNTIME_DIAG_DIR := $(SHARED_ROOT)/kit/kit_runtime_diag
KIT_RENDER_DIR := $(SHARED_ROOT)/kit/kit_render
KIT_WORKSPACE_AUTHORING_DIR := $(SHARED_ROOT)/kit/kit_workspace_authoring
SHARED_CC := $(HOST_CC) $(ARCH_FLAGS)

ifeq ($(wildcard $(CORE_HEADLESS_JOB_DIR)/include/core_headless_job.h),)
CORE_HEADLESS_JOB_DIR := $(SHARED_WORKSPACE_DIR)/core/core_headless_job
endif

CORE_SPACE_LIB := $(SHARED_BUILD_DIR)/libcore_space.a
CORE_BASE_LIB := $(SHARED_BUILD_DIR)/libcore_base.a
CORE_IO_LIB := $(SHARED_BUILD_DIR)/libcore_io.a
CORE_DATA_LIB := $(SHARED_BUILD_DIR)/libcore_data.a
CORE_PACK_LIB := $(SHARED_BUILD_DIR)/libcore_pack.a
CORE_TIME_LIB := $(SHARED_BUILD_DIR)/libcore_time.a
CORE_QUEUE_LIB := $(SHARED_BUILD_DIR)/libcore_queue.a
CORE_SCHED_LIB := $(SHARED_BUILD_DIR)/libcore_sched.a
CORE_JOBS_LIB := $(SHARED_BUILD_DIR)/libcore_jobs.a
CORE_WORKERS_LIB := $(SHARED_BUILD_DIR)/libcore_workers.a
CORE_WAKE_LIB := $(SHARED_BUILD_DIR)/libcore_wake.a
CORE_KERNEL_LIB := $(SHARED_BUILD_DIR)/libcore_kernel.a
CORE_TRACE_LIB := $(SHARED_BUILD_DIR)/libcore_trace.a
CORE_HEADLESS_JOB_LIB := $(SHARED_BUILD_DIR)/libcore_headless_job.a
CORE_THEME_LIB := $(SHARED_BUILD_DIR)/libcore_theme.a
CORE_FONT_LIB := $(SHARED_BUILD_DIR)/libcore_font.a
CORE_PANE_LIB := $(SHARED_BUILD_DIR)/libcore_pane.a
CORE_VIEWPORT2D_LIB := $(SHARED_BUILD_DIR)/libcore_viewport2d.a
KIT_RUNTIME_DIAG_LIB := $(SHARED_BUILD_DIR)/libkit_runtime_diag.a
KIT_RENDER_OBJ := $(HOST_BUILD_ROOT)/kit_render/kit_render.o
KIT_RENDER_BACKEND_NULL_OBJ := $(HOST_BUILD_ROOT)/kit_render/kit_render_backend_null.o
KIT_RENDER_BACKEND_VK_OBJ := $(HOST_BUILD_ROOT)/kit_render/kit_render_backend_vk.o
KIT_RENDER_EXTERNAL_TEXT_OBJ := $(HOST_BUILD_ROOT)/kit_render/kit_render_external_text.o
KIT_WORKSPACE_AUTHORING_OBJ := $(HOST_BUILD_ROOT)/kit_workspace_authoring/kit_workspace_authoring.o
KIT_WORKSPACE_AUTHORING_UI_OVERLAY_OBJ := $(HOST_BUILD_ROOT)/kit_workspace_authoring/kit_workspace_authoring_ui_overlay.o
KIT_WORKSPACE_AUTHORING_UI_FONT_THEME_OBJ := $(HOST_BUILD_ROOT)/kit_workspace_authoring/kit_workspace_authoring_ui_font_theme.o

VK_RENDERER_DIR ?= $(SHARED_ROOT)/vk_renderer
VK_RENDERER_RESOLVED_DIR := $(VK_RENDERER_DIR)
VK_RENDERER_INCLUDE := $(VK_RENDERER_RESOLVED_DIR)/include
VK_RENDERER_STATIC_LIB := $(VK_RENDERER_RESOLVED_DIR)/build/lib/libvkrenderer.a
VK_RENDERER_SRCS := $(wildcard $(VK_RENDERER_RESOLVED_DIR)/src/*.c)
VK_RENDERER_OBJS := $(patsubst $(VK_RENDERER_RESOLVED_DIR)/src/%.c,$(HOST_BUILD_ROOT)/vk_renderer/%.o,$(VK_RENDERER_SRCS))
VK_RUNTIME_DIR ?= $(SHARED_ROOT)/vk_runtime
VK_RUNTIME_INCLUDE := $(VK_RUNTIME_DIR)/include
VK_RUNTIME_SRCS := $(wildcard $(VK_RUNTIME_DIR)/src/*.c)
VK_RUNTIME_OBJS := $(patsubst $(VK_RUNTIME_DIR)/src/%.c,$(HOST_BUILD_ROOT)/vk_runtime/%.o,$(VK_RUNTIME_SRCS))
VK_RUNTIME_AVAILABLE := $(if $(wildcard $(VK_RUNTIME_INCLUDE)/vk_runtime.h),1,)
VK_RUNTIME_MODULE_VERSION := $(strip $(shell cat $(VK_RUNTIME_DIR)/VERSION 2>/dev/null))
VK_RUNTIME_VERSION_CFLAG := -DVK_RUNTIME_BUILD_VERSION=\"$(VK_RUNTIME_MODULE_VERSION)\"
VK_BUILD_LIB := $(TARGET_BUILD_ROOT)/vk/lib/libvkrenderer.a
VK_BUILD_SHADER_DIR := $(TARGET_BUILD_ROOT)/vk/shaders
VK_REQUIRED_SHADERS := fill.vert.spv fill.frag.spv line.vert.spv line.frag.spv textured.vert.spv textured.frag.spv
VK_APP_ENABLED := $(if $(wildcard $(VK_RENDERER_INCLUDE)/vk_renderer.h),1,)
